config/routes.rb
Rails.application.routes.draw do
	root to: "categories#index"

  resources :articles
  resources :categories
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true
  validates :body, presence: true
  validates :category, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles, dependent: :destroy

	validates :name, presence: true

	def to_s
		name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def find_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if(page_title.empty?)
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.haml
= form_for @article, :html => { :class => "form-horizontal article" } do |f|
  = render 'shared/errors', :resource => @article
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-4
      = f.text_field :title, :class => 'form-control'
  .form-group
    = f.label :body, :class => 'control-label col-lg-2'
    .col-lg-4
      = f.text_area :body, :rows => 5, :class => 'form-control'
  .form-group
    = f.label :category_id, :class => 'control-label col-lg-2'
    .col-lg-4
      = f.select :category_id, Category.all.collect{|c| [c.name, c.id]}, {}, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', articles_path, :class => 'btn btn-default'

app/views/articles/edit.html.haml
.page-header
  %h1 Edit Article
= render 'form'

app/views/articles/index.html.haml
.page-header
  %h1 Articles
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Title
      %th Category
      %th Created at
      %th Actions
  %tbody
    - @articles.each do |article|
      %tr
        %td= link_to article.id, article
        %td= article.title
        %td= article.category
        %td= article.created_at
        %td
          = link_to 'Edit', edit_article_path(article), :class => 'btn btn-default btn-xs'
          = link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'
= link_to 'New', new_article_path, :class => 'btn btn-primary'

app/views/articles/new.html.haml
.page-header
  %h1 New Article
= render 'form'

app/views/articles/show.html.haml
.page-header
  %h1 Article
%dl.dl-horizontal
  %dt
    %strong Title:
  %dd= @article.title
  %dt
    %strong Body:
  %dd= @article.body
  %dt
    %strong Category:
  %dd= @article.category
= link_to 'Back', articles_path, :class => 'btn btn-default'
= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-default'
= link_to 'Destroy', @article, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

app/views/categories/_form.html.haml
= form_for @category, :html => { :class => "form-horizontal category" } do |f|
  = render 'shared/errors', :resource => @category
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-4
      = f.text_field :name, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
.page-header
  %h1 Edit Category
= render 'form'

app/views/categories/index.html.haml
.page-header
  %h1 Categories
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Name
      %th Created at
      %th Actions
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.id, category
        %td= category.name
        %td= category.created_at
        %td
          = link_to 'edit', edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to 'destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'
= link_to 'New', new_category_path, :class => 'btn btn-primary'

app/views/categories/new.html.haml
.page-header
  %h1 New Category
= render 'form'

app/views/categories/show.html.haml
.page-header
  %h1 Category
%dl.dl-horizontal
  %dt
    %strong Name:
  %dd= @category.name
= link_to 'Back', categories_path, :class => 'btn btn-default'
= link_to 'Edit', edit_category_path(@category), :class => 'btn btn-default'
= link_to 'Destroy', @category, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "Article Manager"
          = csrf_meta_tags
          = stylesheet_link_tag "application", :media => "all"
          = javascript_include_tag "application"
          
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        = link_to 'Article Manager', root_path, :class=> 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Categories", categories_path
            %li= link_to "Articles", articles_path
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/shared/_errors.html.haml
- if resource.errors.any?
  .col-lg-offset-1.col-lg-10
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(resource.errors.count, "error")
          prohibited this #{resource.class.name.downcase} from being saved:
      .panel-body
        %ul
          - resource.errors.full_messages.each do |msg|
            %li= msg